output "appregistration_client_id" {
  description = "The Client ID for the application."
  value       = azuread_application.adappregistration.client_id
  sensitive   = false
}

output "appregistration_object_id" {
  description = "The Entra Object ID for the application."
  value       = azuread_application.adappregistration.object_id
  sensitive   = false
}

output "appregistration_id" {
  description = "The Terraform resource ID for the application, for use when referencing this resource in your Terraform configuration."
  value       = azuread_application.adappregistration.id
}

output "appregistration_client_secret" {
  description = "The password for this application, which is generated by Azure Active Directory."
  value       = azuread_application_password.ad_application_password.value
  sensitive   = true
}

output "display_name" {
  description = "The name of the application."
  value       = azuread_application.adappregistration.display_name
}

output "serviceprincipal_object_id" {
  description = "The Entra Object ID for the applications ServicePrincipal."
  value       = azuread_service_principal.ad_service_principal.object_id
  sensitive   = false
}

output "identifier_uris" {
  description = "A set of user-defined URI(s) that uniquely identify an application within its Azure AD tenant, or within a verified custom domain if the application is multi-tenant."
  value       = azuread_application.adappregistration.identifier_uris
}

output "oauth2_permission_scope_ids" {
  description = "A mapping of OAuth2.0 permission scope values to scope IDs, intended to be useful when referencing permission scopes in other resources in your configuration."
  value       = azuread_application.adappregistration.oauth2_permission_scope_ids
}

output "app_role_ids" {
  description = "A mapping of App Role values to role IDs, intended to be useful when referencing app roles in other resources in your configuration."
  value       = azuread_application.adappregistration.app_role_ids
}
