variable "authorized_app_id" {
  description = "Authorized client application in settings 'Expose an API'"
  type        = string
  default     = ""
  nullable    = true
}

variable "name" {
  description = "The name of the App Registration."
  type        = string
  default     = ""
  nullable    = false
}

variable "resourceIdentifier" {
  description = "Identifier of the resource e.g. api, app, or empty."
  type        = string
  default     = ""
}

variable "owners" {
  description = "IDs of the owner"
  type        = list(string)
  default     = [""]
  nullable    = false
}

variable "sign_in_audience" {
  description = <<EOT
    The Microsoft account types that are supported for the current application.
    Must be one of [AzureADMyOrg], [AzureADMultipleOrgs], [AzureADandPersonalMicrosoftAccount] or [PersonalMicrosoftAccount]. Defaults to AzureADMyOrg.
  EOT
  type        = string
  default     = "AzureADMyOrg"
}

variable "environment" {
  description = "This variable specifies the current environment. Must be on of [dev],[test] or [prod]"
  type        = string
  default     = ""
  nullable    = false
}

variable "expiration_date" {
  description = "The expiration date used for secrets etc."
  type        = string
  default     = "2099-12-31T23:59:59Z"
}

variable "is_frontend" {
  description = "Distinguish between frontend and backend registration"
  type        = bool
  default     = false
}

variable "required_resource_access" {
  description = <<EOT
  Required resource access for this application. A collection of required_resource_access blocks as documented below. Each block supports the following:
  [resource_access] (Required) A collection of resource_access blocks as documented below, describing OAuth2.0 permission scopes and app roles that the application requires from the specified resource.
  [resource_app_id] (Required) The unique identifier for the resource that the application requires access to. This should be the Application ID of the target application.
  EOT
  type = list(
    object({
      resource_app_id = string
      resource_access = list(
        object({
          id   = string
          type = string
      }))
  }))
  nullable = false
}

variable "app_roles" {
  description = <<EOT
  (Optional) A collection of app_role blocks as documented below:
  [description] (Required) Description of the app role that appears when the role is being assigned and, if the role functions as an application permissions, during the consent experiences.
  [display_name] (Required) Display name for the app role that appears during app role assignment and in consent experiences.
  [enabled] (Optional) Determines if the app role is enabled. Defaults to true.
  [id] (Required) The unique identifier of the app role. Must be a valid UUID. Value will be auto generated by a random_uuid resource.
  EOT
  type = list(object({
    # id                   = string
    display_name         = string
    allowed_member_types = list(string)
    description          = string
    value                = string
    enabled              = bool
  }))
  nullable = true
}

variable "web_redirect_uris" {
  type    = list(string)
  default = []
}

variable "azuread_service_principal_assignment_required" {
  description = "Whether this service principal requires an app role assignment to a user or group before Azure AD will issue a user or access token to the application. Defaults to false."
  type        = bool
  default     = false
}

variable "group_membership_claims" {
  description = <<EOT
  Configures the groups claim issued in a user or OAuth 2.0 access token that the app expects.
  Available options are:
  - None: No groups claim is issued in the token.
  - SecurityGroup: Groups claim includes the security groups.
  - All: Groups claim includes all types of groups.
  - DirectoryRole: Groups claim includes directory roles.
  EOT
  type        = set(string)
  default     = ["None"]
  nullable    = false
}
