schedules:
- cron: 0 0 * * mon-fri # cron syntax defining a schedule
  displayName: Scheduler # friendly name given to a specific schedule
  branches:
    include:
    - dev
  always: true # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.

trigger: none

parameters:
  - name: templateVersion
    displayName: Version tag of the used templates
    type: string
    default: 1.0

pool:
  vmImage: ubuntu-latest

variables:
  - group: kv-azure-devops-gbsw

name: Renovate-$(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
  - repository: templates
    name: Pipeline-Templates/pipeline-template-renovate
    type: git
    ref: refs/tags/${{ parameters.templateVersion }}

steps:
  - checkout: self
  - checkout: templates

  - template: renovate.yml@templates
    parameters:
      githubComToken: "$(GITHUB_COM_TOKEN)"
      autoApprovePatch: true
      autoMergePatch: true