parameters:
  - name: templateVersion
    displayName: Version tag of the used templates
    type: string
    default: 0.0.10
  - name: jdkVersion
    displayName: JDK Version Number [LTS 17]
    type: string
    default: 17
    values:
      - 17
      - 21 #scheduled for release on September 19, 2023
  - name: sonarCloudProjectName
    displayName: Project Name [terraform-azuread-appregistration-api]
    type: string
    default: terraform-azuread-appregistration-api

trigger:
  branches:
    include:
      - refs/heads/dev

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: templates
    name: Pipeline-Templates/pipeline-template-sonarCloud
    type: git
    ref: refs/tags/0.0.10

name: $(date:yyyyMMdd)$(rev:.r)

steps:
  - template: terraform.yml@templates
    parameters:
      jdkVersion: 17
      sonarCloudProjectName: terraform-azuread-appregistration-api
      sonarCloudEndpointName: SonarCloud