parameters:
  - name: templateVersion
    displayName: Version tag of the used templates
    type: string
    default: 0.0.10
  - name: jdkVersion
    displayName: JDK Version Number [LTS 17]
    type: string
    default: 17
    values:
      - 17
      - 21 #scheduled for release on September 19, 2023
  - name: sonarCloudProjectName
    displayName: Project Name [terraform-azuread-appregistration-api]
    type: string
    default: terraform-azuread-appregistration-api

trigger:
  branches:
    include:
      - main #TODO change to default branch

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: templates
    name: Pipeline-Templates/pipeline-template-sonarCloud
    type: git
    ref: refs/tags/parameters['templateVersion']

name: $(date:yyyyMMdd)$(rev:.r)

steps:
  - template: terraform.yml@templates
    parameters:
      jdkVersion: parameters['jdkVersion']
      sonarCloudProjectName: parameters['sonarCloudProjectName']