parameters:
  - name: templateVersion
    displayName: Version tag of the used templates
    type: string
    default: 0.1
  - name: sonarCloudProjectName
    displayName: Project Name [terraform-azuread-appregistration-api]
    type: string
    default: terraform-azuread-appregistration-api

trigger:
  branches:
    include:
      - refs/heads/dev

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: templates
    name: Pipeline-Templates/pipeline-template-sonarCloud
    type: git
    ref: refs/tags/${{ parameters.templateVersion }}

name: $(date:yyyyMMdd)$(rev:.r)

steps:
  - template: terraform.yml@templates
    parameters:
      sonarCloudProjectName: ${{ parameters.sonarCloudProjectName }}