trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: templates
    name: Pipeline-Templates/pipeline-template-sonarCloud
    type: git
    ref: refs/tags/0.0.10

name: $(date:yyyyMMdd)$(rev:.r)

steps:
  - template: terraform.yml@templates
    parameters:
      jdkVersion: 17
      sonarCloudProjectName: terraform-azuread-appregistration-api